theme = "onedarker"

[editor]
auto-info = true
completion-timeout = 5
cursorline = true
default-yank-register = "+"
idle-timeout = 5
line-number = "relative"
inline-diagnostics.cursor-line = "hint"
lsp.auto-signature-help = false
smart-tab.enable = false
soft-wrap.enable = true

[editor.cursor-shape]
normal = "block"
insert = "bar"

