theme = "dark_plus_custom"

[editor]
line-number = "relative"
text-width = 100
completion-trigger-len = 3
inline-diagnostics = { cursor-line = "warning", other-lines = "disable" }

[editor.lsp]
auto-signature-help = false
display-inlay-hints = false
display-messages = false

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""
