
[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style=file"] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "--stdin-filename", "%{buffer_name}", "-"] }
