
[[language]]
name = "c"
auto-format =  false
formatter = { command = "clang-format", args = ["-style", "{IndentWidth: 4, TabWidth: 4, UseTab: Never}"] }
   
[[language]]
name = "python"
auto-format = false 
formatter = { command = "ruff", args = ["format", "--stdin-filename", "%{buffer_name}", "-"] }
