inherits = "ayu_mirage"

"ui.background" = {}
"ui.text" = {}
"ui.menu" = {}
"ui.popup" = {}
"ui.window" = {}

"ui.statusline" = { fg = "#1A1A1A", bg = "#999999"}
"ui.statusline.inactive" = { fg = "black", bg = "gray" }
